name: frontend_ci

on:
  push:
    branches:
      - dev/FE
    paths: "frontend/**"
  pull_request:
    branches:
      - dev/FE
    paths: "frontend/**"

defaults:
  run:
    working-directory: ./frontend

jobs:
  Cypress-Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitCode
        uses: actions/checkout@v3

      - name: install dependencies
        uses: npm install

      - name: dev start
        uses: npm run dev

      - name: Run Cypress Test
        uses: cypress-io/github-action@v5
        with:
          command: npm run test
