name: frontend_ci

on:
  push:
    branches:
      - dev/FE
    paths: "frontend/**"
  pull_request:
    branches:
      - dev/FE
    paths: "frontend/**"

defaults:
  run:
    working-directory: ./frontend

jobs:
  Cypress-Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitCode
        uses: actions/checkout@v3

      - name: Setup node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: install dependencies
        run: npm install

      - name: Cypress run
        working-directory: "/home/runner/work/2023-baton/2023-baton/frontend"
        uses: cypress-io/github-action@v6
        with:
          start: npm run test
