name: frontend_ci

on:
  push:
    branches:
      - dev/FE
    paths: "frontend/**"
  pull_request:
    branches:
      - dev/FE
    paths: "frontend/**"

defaults:
  run:
    working-directory: ./frontend

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm install

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          start: npm run test
